trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job:
    steps:
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: ls -l $(Build.SourcesDirectory)
    - bash: ls -l $(Build.ArtifactStagingDirectory)
    - bash: ls -l $(System.DefaultWorkingDirectory)
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'Dockerfile'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -l $(Build.ArtifactStagingDirectory)
    
- stage: DeployDev
  jobs:
  - job: StartDeploy
    steps:
    - bash: ls -l $(Build.ArtifactStagingDirectory)

# - stage: DeployQA
#   dependsOn: Build
#   jobs:
#   - job: StartDeploy
#     steps:
#     - script: echo "Starting with the deployment"
#       displayName: "Start the deployment!"
#   - job: CompleteDeploy
#     dependsOn: StartDeploy
#     steps:
#     - bash: echo "Deployment is complete!"
#       displayName: 'Running the deployment stage'
