trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job:
    steps:
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: ls -l $(Build.SourcesDirectory)
    - bash: ls -l $(Build.ArtifactStagingDirectory)
    - bash: ls -l $(System.DefaultWorkingDirectory)
    
    - task: CopyFiles@2
      displayName: Copy files to staging directory
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'Dockerfile/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -l $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: Publish the artifacts to DeployDev stage
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifest'
        publishLocation: 'Container'
    
- stage: DeployDev
  jobs:
  - job: StartDeploy
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'manifest'
        downloadPath: '$(System.ArtifactsDirectory)'
        cleanDestinationFolder: true


# - stage: DeployQA
#   dependsOn: Build
#   jobs:
#   - job: StartDeploy
#     steps:
#     - script: echo "Starting with the deployment"
#       displayName: "Start the deployment!"
#   - job: CompleteDeploy
#     dependsOn: StartDeploy
#     steps:
#     - bash: echo "Deployment is complete!"
#       displayName: 'Running the deployment stage'
