trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job:
    steps:
    - script: echo Hello, world! $(TestVariable)
      displayName: 'Run a one-line script'
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    
# - stage: DeployDev
#   variables:
#     environment: Dev
#   jobs:
#   - job: StartDeploy
#     steps:
#     - script: echo "Starting with the deployment in $(environment)"
#       displayName: "Start the deployment!"
#   - job: CompleteDeploy
#     dependsOn: StartDeploy
#     steps:
#     - bash: echo "Deployment is complete in $(environment)!"
#       displayName: 'Running the deployment stage'

# - stage: DeployQA
#   dependsOn: Build
#   jobs:
#   - job: StartDeploy
#     steps:
#     - script: echo "Starting with the deployment"
#       displayName: "Start the deployment!"
#   - job: CompleteDeploy
#     dependsOn: StartDeploy
#     steps:
#     - bash: echo "Deployment is complete!"
#       displayName: 'Running the deployment stage'
