trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: BuildImage
  jobs:
  - job:
    steps:
    # - bash: echo $(Build.BuildNumber)
    # - bash: echo $(Build.BuildId)
    # - bash: ls -l $(Build.SourcesDirectory)
    # - bash: ls -l $(Build.ArtifactStagingDirectory)
    # - bash: ls -l $(System.DefaultWorkingDirectory)
    
    - task: CopyFiles@2
      displayName: Copy Dockerfile to staging directory
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/Dockerfile'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -l $(Build.ArtifactStagingDirectory)

    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'nihals/azure-nginx'
        command: 'build'
        Dockerfile: '$(Build.ArtifactStagingDirectory)/Dockerfile'
        addPipelineData: false
        addBaseImageData: false
        tags: $(Build.BuildId)
    
    #Save the image to tar file
    - script: docker save nihals/azure-nginx:$(Build.BuildId) -o $(Build.ArtifactStagingDirectory)/azure-nginx.tar

    - task: PublishBuildArtifacts@1
      displayName: Publish the artifacts to DeployImage stage
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifest'
        publishLocation: 'Container'
    
- stage: DeployImage
  jobs:
  - job: StartDeploy
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'manifest'
        downloadPath: '$(System.ArtifactsDirectory)'
        cleanDestinationFolder: true

    #Load the image to the new agent from the archive file
    - script: docker load -i $(System.ArtifactsDirectory)/manifest/azure-nginx.tar


    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub-connection'
        repository: 'nihals/azure-nginx'
        command: 'push'
        tags: $(Build.BuildId)
