trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
- stage: Build
  jobs:
  - job:
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'  
      
- stage: Deploy
  jobs:
  - job:
    steps:
    - script: echo "Starting with the deployment"
      displayName: "Start the deployment!"
  - job:
    steps:
    - bash: echo "Deployment is complete!"
      displayName: 'Running the deployment stage'


